const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("desktop", {
  chooseImages: () => ipcRenderer.invoke("choose-images"),
  addRecentDocuments: (paths) => ipcRenderer.invoke("add-recent-documents", paths),
  pasteImage: () => ipcRenderer.invoke("paste-image"),
  pasteFiles: () => ipcRenderer.invoke("paste-files"),
  importDroppedImage: (bytes, mimeType) => ipcRenderer.invoke("import-dropped-image", bytes, mimeType),
  importDroppedImageDataUrl: (dataUrl) => ipcRenderer.invoke("import-dropped-image-data-url", dataUrl),
  renderImage: (filePath, options) => ipcRenderer.invoke("render-image", filePath, options),
  openDitherComparison: (image, options) => ipcRenderer.invoke("open-dither-comparison", image, options),
  getDitherComparison: () => ipcRenderer.invoke("get-dither-comparison"),
  applyDitherComparison: (dither) => ipcRenderer.invoke("apply-dither-comparison", dither),
  closeDitherComparison: () => ipcRenderer.invoke("close-dither-comparison"),
  onDitherComparisonApply: (callback) => ipcRenderer.on("dither-comparison-apply", (_event, dither) => callback(dither)),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  onOpenImages: (callback) => ipcRenderer.on("open-images", (_event, paths) => callback(paths)),
  onMenuAction: (callback) => ipcRenderer.on("menu-action", (_event, action) => callback(action)),
  onBluetoothDevices: (callback) => ipcRenderer.on("bluetooth-devices", (_event, devices) => callback(devices)),
  onPrinterDiscoveryTimeout: (callback) => ipcRenderer.on("printer-discovery-timeout", () => callback()),
  selectBluetoothDevice: (deviceId) => ipcRenderer.invoke("select-bluetooth-device", deviceId),
  preparePrinterDiscovery: (names, timeout) => ipcRenderer.sendSync("prepare-printer-discovery", names, timeout),
  cancelBluetoothSelection: () => ipcRenderer.invoke("cancel-bluetooth-selection"),
  openBluetoothSettings: () => ipcRenderer.invoke("open-bluetooth-settings"),
  showNotification: (notification) => ipcRenderer.invoke("show-notification", notification),
  getAppInfo: () => ipcRenderer.invoke("app-info"),
  setQuitOnWindowClose: (enabled) => ipcRenderer.invoke("set-quit-on-window-close", enabled),
  updatePrinterMenu: (state) => ipcRenderer.send("update-printer-menu", state),
  getAccentColor: () => ipcRenderer.invoke("get-accent-color"),
  onAccentColorChanged: (callback) => ipcRenderer.on("accent-color-changed", (_event, color) => callback(color)),
});
